### ISSUE TITLE
arm version for docker images of server and repository

### ISSUE THREAD

**Issue by yaroslav-007** [hashgraph/hedera-sourcify#139]
### Description

Hello,

We are currently working on issue [Add support for smart contract verification #558 ](https://github.com/hashgraph/hedera-local-node/issues/558) in local node repo.

I believe there are missing ARM images of `ghcr.io/hashgraph/hedera-sourcify:server-main` and `ghcr.io/hashgraph/hedera-sourcify:repository-main` 

### Steps to reproduce

When I run `docker-compose  -f docker-compose-hedera.yaml up` (without building the images on  M1 Mac chip) i got the error:
`no matching manifest for linux/arm64/v8 in the manifest list entries`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by kuzdogan** [comment]
Just ran into this. You can refer to our arm CI setup to set this :) https://github.com/ethereum/sourcify/blob/staging/.circleci/config.yml

**Comment by acuarica** [comment]
Hi @yaroslav-007, thanks for opening this. It seems it was removed due to some issues in CI
- https://github.com/hashgraph/hedera-sourcify/pull/51

I'm going to check with @svienot how we can re-include it.

**Comment by isavov** [comment]
> Hi @yaroslav-007, thanks for opening this. It seems it was removed due to some issues in CI
> 
>     * [Remove linux/arm64 platform for the build of server and repository images #51](https://github.com/hashgraph/hedera-sourcify/pull/51)
> 
> 
> I'm going to check with @svienot how we can re-include it.

I'm currently testing a workaround for the issue that was the reason for disabling arm images (tldr: they were failing because they were too slow). I expect to open a PR soon.

**Comment by acuarica** [comment]
Hi @yaroslav-007, a quick update regarding this issue. We now publish images for both platforms. See packages `server`, `repository` and `ui` in https://github.com/orgs/hashgraph/packages?repo_name=hedera-sourcify. Please note that the new images are published under a new name scheme[1], _e.g._, `ghcr.io/hashgraph/hedera-sourcify/server:main`.

This should solve the issue, let us know if you need more support.

---

- [1] https://github.com/hashgraph/hedera-sourcify/issues/177

**Comment by yaroslav-007** [comment]
Hello,

I was able to perform test with arm64 architecture.

Thanks for the support
