### ISSUE TITLE
A way to configure hedera-json-rpc-relay address

### ISSUE THREAD

**Issue by yaroslav-007** [hashgraph/hedera-sourcify#140]
### Problem

Hello,

We are currently working on issue [Add support for smart contract verification #558 ](https://github.com/hashgraph/hedera-local-node/issues/558) in local node repo.

We would like to be able to configure (preferably by variable) the address for `hedera-json-rpc-relay` for localnode in https://github.com/hashgraph/hedera-sourcify/blob/d6034bb53ca5412acc1a7300a99abca3f2d92423/src/sourcify-chains.ts#L47

### Solution

Adding variable for hedera rpc relay address

**Comment by acuarica** [comment]
Hi @yaroslav-007, after PR https://github.com/hashgraph/hedera-sourcify/pull/164, there is a new mechanism to use custom chains. You just need to mount a custom `sourcify-chains.json` to configure networks. See `compose.yaml` and `sourcify-chains.json` for more details.

https://github.com/hashgraph/hedera-sourcify/blob/f41d610a3f6fa9ffc56f47186abd666cfd3b8f54/compose.yaml#L88-L99

https://github.com/hashgraph/hedera-sourcify/blob/f41d610a3f6fa9ffc56f47186abd666cfd3b8f54/sourcify-chains.json#L14-L20

I believe this should solve the issue, please let us know if you need more support.

**Comment by yaroslav-007** [comment]
Hello,
The new mechanism for using custom chains is working as per my tests/implementation.

Thanks for the support
