### ISSUE TITLE
Add metric support for services

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-sourcify#40]
### Problem

The open-source sourcify repo has in built grafana metrics support which we were not able to leverage in initial usgage

### Solution

Explore and add capabilities to enable in built metrics to flow and be scraped by grafana services

**Comment by svienot** [comment]
The sourcify `environments` folder contains set-up to launch various containers related to the monitoring of the systems:
 - _cadvisor_: exports container-based metrics
 - _node exporter_: exports host and OS-based metrics
 - _promtail_: exports local logs
 - _loki_: log aggregator
 - _grafana_: visualisation
 - _nginx_ prometheus exporter: exports nginx metrics
 - _prometheus_: metrics and alerting

I understand this set-up is neither complete, nor up-to-date and it looks like it no longer exists today in the upstream sourcify repository.
There are no application-specific metrics in the code today.

I got a reply on this subject a while ago from marco castignoli who is one of the **sourcify.dev** developers:

"we are currently monitoring every metric using a separate grafana service that monitors our kubernetes pods, everything about grafana / node_exporter / cadvisor you read in the repo is old. 
We also have an event manager class that logs different kind of events that can be used to track different sourcify specific metrics. These are the events that we monitor:
```
		"Verification.MatchStored"
		"Server.SourcifyChains.Warn"
		"SourceFetcher.UsingFallback"
		"SourceFetcher.NewSubscription"
		"SourceFetcher.Cleanup"
		"SourceFetcher.FetchFailed"
		"SourceFetcher.FetchingSuccessful"
```
Not many actually, we are thinking about removing this EventManager...  "

From this it looks like one of the events logged: `"Verification.MatchStored"`   could be helpful to track the verified contract flow.
