### ISSUE TITLE
Add API test suite

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-sourcify#45]
### Problem

The server supports a range of APIs available to developers that don't go through the UI.
Currently don't have a set of tests to confirm their ongoing functionality

### Solution

Add a test suite that covers endpoints noted under api-docs

### Alternatives

Explore if the forked code repo already has these tests. If so expose them in CI runs and allow them to be run against remote environments

**Comment by Nana-EC** [comment]
@acuarica did your enabling of API tests cover this or is there more test coverage to add?

**Comment by acuarica** [comment]
There are some endpoints, _e.g._, create2 related endpoints that are uncovered. However we can close this in favor of

- https://github.com/hashgraph/hedera-sourcify/issues/97
