### ISSUE TITLE
IPFS hash to be clickable `ipfs://` link?

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-sourcify#56]
### Problem

IPFS hash on main contract page is selectable for copy but isn't clickable.

### Solution

Can the IPFS hash for in the main contract page be an actual `ipfs://` link?  Alternatively, instead of being a link (which sometimes interferes with selection in order to copy) maybe have one of those "external link" icons?
<img width="110" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/117694041/c467244f-8246-4776-85e4-a86065973746">

### Alternatives

Or maybe a `dweb` link whatever those are.

**Comment by acuarica** [comment]
Hi @david-bakin-sl, thanks for sending this. Could you provide more details about where this happens?

**Comment by david-bakin-sl** [comment]
This may have been for an older version of the UI, perhaps even the first adopted version (before our productization).  As I recall the UI was fairly bare then.

**Comment by acuarica** [comment]
After discussing offline with @david-bakin-sl, this might have been an older version of hashscan when displaying verified contracts. This issue doesn't appear in hashscan anymore, closing this.
