### ISSUE TITLE
Add a Link to the Metadata Section at docs.hedera.com for Generating Metadata File

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-sourcify#62]
### Problem

I was trying to verify a smart contract I had previously deployed. When I adding in my .sol file I was prompted to add in my metadata file.
![Untitled (1)](https://github.com/hashgraph/hedera-sourcify/assets/18725916/185ca385-6286-4ebe-a772-e90d5bc588e7)

I was trying to figure out how to generate the metadata file. I googled "How to get my smart contract metadata hedera" and ran into the Verifying Smart Contract documentation. In that section, there is a section on how to generate the metadata file. 
![Untitled (2)](https://github.com/hashgraph/hedera-sourcify/assets/18725916/9b1aaeac-4ae8-485e-9e7b-cf4c9b58e76f)

### Solution

Add a link to this [metadata section](https://docs.hedera.com/hedera/core-concepts/smart-contracts/verifying-smart-contracts-beta#the-metadata-file) to [verify.hashscan.io/#/](http://verify.hashscan.io/#/) to help other developers who may require guidance on creating the metadata file.

**In addition, adding a note stating:** 
It's important to note that when generating the metadata it is best to use the same tool you use to compile & deploy your smart contract.

**Comment by quiet-node** [comment]
Hello @a-ridley thanks for openning the ticket and sorry for the late reply. So, with your suggestion, it could look like this
<img width="1029" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/66233296/008e152c-adc4-41b1-89fd-d3dba95ef17e">
. The Lerarn more button will open a new link to the metadata section you mentioned. What do you think?

**Comment by a-ridley** [comment]
This looks great! Thanks @quiet-node  🥳
