### ISSUE TITLE
Enable CI unit tests for `contract-call-decoder`

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-sourcify#94]
The unit tests for `contract-call-decoder`, `cd packages/contract-call-decoder && npm run test`, fail on CI because of an external IPFS request timeout.

Enable those tests in CI by avoiding the external IPFS request.

**Comment by Nana-EC** [comment]
If possible maybe we can point it to a local IPFS node spun up as part of CI

**Comment by acuarica** [comment]
@Nana-EC I've checked the Sourcify repo and they've skipped the problematic test as well https://github.com/ethereum/sourcify/commit/cba1738443de0319f7affbd827ae7e924875d79b.

We could take the same approach and skip the test to enable CI testing, and figure out later how to fix the test.
